name: worker

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

concurrency:
  group: worker-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Mask Worker URL
        run: echo "::add-mask::${{ secrets.WORKER_URL }}"
      - name: Mask Cloudflare account name
        run: echo "::add-mask::${{ secrets.CLOUDFLARE_MAIL }}"
      - uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: worker
          command: deploy
